/** Standard API error codes — DevSpec Full §10 */
export const ErrorCodes = {
  RENT_NOT_AVAILABLE: 'RENT_NOT_AVAILABLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CART_BUY_ONLY: 'CART_BUY_ONLY',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INSUFFICIENT_COINS: 'INSUFFICIENT_COINS',
  NO_ENTITLEMENT: 'NO_ENTITLEMENT',
  FORBIDDEN: 'FORBIDDEN',
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  DUPLICATE_ENTITLEMENT: 'DUPLICATE_ENTITLEMENT',
  DUPLICATE_CART_ITEM: 'DUPLICATE_CART_ITEM',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const HttpStatus = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL: 500,
} as const;
